# Generated by Django 5.1.4 on 2026-03-25 15:07

from django.db import migrations


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            -- 1. Remove public (anon) full access permissions
            REVOKE ALL ON TABLE public.users_user FROM anon;
            REVOKE ALL ON TABLE public.resumes_resume FROM anon;
            REVOKE ALL ON TABLE public.payments_payment FROM anon;
            REVOKE ALL ON TABLE public.django_session FROM anon;

            -- 2. Enable RLS
            ALTER TABLE public.users_user ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.resumes_resume ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.payments_payment ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.django_session ENABLE ROW LEVEL SECURITY;

            -- 3. Add policies
            -- users_user: Allow users to read/update ONLY their own data
            CREATE POLICY "users_read_own_data" ON public.users_user
                FOR SELECT
                USING (id::text = auth.uid()::text);
                
            CREATE POLICY "users_update_own_data" ON public.users_user
                FOR UPDATE
                USING (id::text = auth.uid()::text);

            -- resumes_resume: Allow access only where resume.user_id = auth.uid()
            CREATE POLICY "resumes_access_own" ON public.resumes_resume
                FOR ALL
                USING (user_id::text = auth.uid()::text);

            -- payments_payment: Only allow access to authenticated users, Restrict reads to own records
            CREATE POLICY "payments_auth_read_own" ON public.payments_payment
                FOR SELECT
                TO authenticated
                USING (user_id::text = auth.uid()::text);
        """)

def reverse_rls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            DROP POLICY IF EXISTS "users_read_own_data" ON public.users_user;
            DROP POLICY IF EXISTS "users_update_own_data" ON public.users_user;
            DROP POLICY IF EXISTS "resumes_access_own" ON public.resumes_resume;
            DROP POLICY IF EXISTS "payments_auth_read_own" ON public.payments_payment;

            ALTER TABLE public.users_user DISABLE ROW LEVEL SECURITY;
            ALTER TABLE public.resumes_resume DISABLE ROW LEVEL SECURITY;
            ALTER TABLE public.payments_payment DISABLE ROW LEVEL SECURITY;
            ALTER TABLE public.django_session DISABLE ROW LEVEL SECURITY;

            GRANT ALL ON TABLE public.users_user TO anon;
            GRANT ALL ON TABLE public.resumes_resume TO anon;
            GRANT ALL ON TABLE public.payments_payment TO anon;
            GRANT ALL ON TABLE public.django_session TO anon;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_premium_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RunPython(apply_rls, reverse_rls)
    ]
